name: Ruby on Rails Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Run RuboCop
        run: bundle exec rubocop

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Build Tailwind assets
        env:
          RAILS_ENV: test
        run: bundle exec rails tailwindcss:build

      - name: Setup database
        env:
          RAILS_ENV: test
        run: bundle exec rails db:prepare

      - name: Run tests
        env:
          RAILS_ENV: test
        run: bundle exec rails test
